name: 'Create Github Deployment Status'
description: 'Update the status of a deployment by creating a new status'
author: 'Unacast'
inputs: 
  github_token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  status:
    description: 'The status to create. Can be one of error, failure, inactive, in_progress, queued pending, or success'
    required: true
  description:
    description: 'The description to create. Restricted to 140 chars'
    required: false
    default: ""
  environment_url:
    description: 'Sets the URL for accessing your environment'
    required: false
    default: ""
  auto_inactive:
    description: "Adds a new inactive status to all prior non-transient, non-production environment deployments with the same repository and environment name as the created status's deployment. An inactive status is only added to deployments that had a success state."
    required: false
    default: true    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: ['${{ inputs.status }}', '${{ inputs.description }}', '${{ inputs.environment_url }}', ${{ inputs.auto_inactive }}]
branding:
  icon: 'send'  
  color: 'green'
