name: Test, lint and build

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Test
        uses: docker://bats/bats
        with:
          args: test/deployment-get-id.bats
      - name: Lint
        uses: docker://koalaman/shellcheck
        with:
          args: bin/deployment-create-status bin/deployment-get-id
      - name: Docker build
        run: docker build -t actions-github-deployment-status .
