name: Test, lint and build

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Test
        uses: docker://bats/bats
        with:
          args: test/deployment-get-id.bats
      - name: Lint
        uses: docker://koalaman/shellcheck
        with:
          args: bin/deployment-create-status bin/deployment-get-id
      - name: Docker build
        run: docker build -t actions-github-deployment-status .

  gh-tagged-release:
    name: Tagged release
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=match::true
          fi

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: steps.check-tag.outputs.match == 'true'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            Dockerfile
            action.yml
            bin/
