on: push
name: Build
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test
      uses: docker://bats/bats      
      with:
        args: test/deployment-get-id.bats
    - name: Lint
      uses: docker://koalaman/shellcheck
      with:
        args: bin/deployment-create-status bin/deployment-get-id
    - name: Docker build
      run: make build
    - name: Publish Filter
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: Docker Login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY_URL" -u "$DOCKER_USERNAME" --password-stdin
    - name: Publish
      run: make publish
